version: "3.9"

services:
  game-server:
    build: ./server
    container_name: mmo_server
    restart: always
    ports:
      - "2567:2567"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mmo
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18
    container_name: mmo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mmo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: mmo_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
