services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mmo_server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
    command: npm run dev
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mmo_client
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
    command: npm run dev -- --host 0.0.0.0 --port 3001
    depends_on:
      - server
    restart: unless-stopped
