export const enum ExceptionCodeEnum {
  MYSQL_SERVICE__QUERY_ERR = "MYSQ-SERVICE-000-QRERR",
  MYSQL_SERVICE__CONN_ERR = "MYSQL-SERVICE-001-CNERR",
  REDIS_SERVICE__QUERY_ERR = "REDIS-SERVICE-000-QRERR",
  REDIS_SERVICE__CONN_ERR = "REDIS-SERVICE-001-CNERR",
  VALIDATION_UTIL__ERR = "VALID-001-ERR",
  EXPRESS_APP__START_ERR = "EXPRESS-001-ERR",
  CRON_TASK__GENERAL_PROCEEDING_ERR = "CRON-TASK-PROCEEDING-003-TSERR",
  AXIOS__ERR = "AXIOS-REQ__001-ERR",
  TRACKER__ERR = "TRACKER__000-ERR",
}
